name: check-links
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 0
      LINKS_PROJECT: "src/TestLinks"
    steps:
    - name: git checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
    - name: dotnet run
      run: dotnet run --project $LINKS_PROJECT
