name: check-links
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 0
      LINKS_PROJECT: "src/TestLinks"
    steps:
    - name: git checkout
      uses: actions/checkout@v1
    - name: debug environment
      run: |
        echo $LINKS_PROJECT
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: dotnet build
      run: dotnet build --nologo --configuration Release $LINKS_PROJECT
    - name: dotnet run
      run: dotnet run --nologo --project $LINKS_PROJECT